version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Abcd@1234
      MYSQL_DATABASE: product-catalog
    volumes:
      - ./mysql_data:/var/lib/mysql
  springboot:
    build: .
    container_name: springboot_app
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product-catalog
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abcd@1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    depends_on:
      - mysql
volumes:
  - mysql_data:


